import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";


export const metadata = {
  title: "Last Path Services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
